
name: Swift Package Tests

on:
  workflow_call:

jobs:
  test:
    - name: Checkout
      uses: actions/checkout@v3
        
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.0.1'

    - name: Run tests
      run: swift test --enable-code-coverage

    - name: Gather code coverage
      run: xcrun llvm-cov export -format="lcov" .build/debug/ChessKitPackageTests.xctest/Contents/MacOS/ChessKitPackageTests -instr-profile .build/debug/codecov/default.profdata > coverage_report.lcov

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage_report.lcov
