
name: Swift Package Tests

on:
  workflow_call:
    inputs:
      test_bundle:
        required: true
        type: string

jobs:
  test:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      - name: Run tests
        run: swift test --enable-code-coverage

      - name: Gather code coverage
        run: xcrun llvm-cov export -format="lcov" .build/debug/${{ inputs.test_bundle }}.xctest/Contents/MacOS/${{ inputs.test_bundle }} -instr-profile .build/debug/codecov/default.profdata > coverage_report.lcov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage_report.lcov

      - name: Run Periphery scan
        run: |
          brew update
          brew install peripheryapp/periphery/periphery
          periphery scan --skip-build --strict